Refactor deploy.yml to handle failure in retrieving EC2 Public IP

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -53,7 +53,13 @@ jobs:
     - name: Get EC2 Public IP
       id: ec2_ip
       run: |
-        echo "EC2_PUBLIC_IP=$(terraform output -raw ec2_public_ip)" >> $GITHUB_ENV
+        EC2_PUBLIC_IP=$(terraform output -raw ec2_public_ip 2> /dev/null || echo "")
+        if [ -z "$EC2_PUBLIC_IP" ]; then
+          echo "Failed to retrieve EC2 Public IP"
+          exit 1
+        fi
+        echo "EC2_PUBLIC_IP=$EC2_PUBLIC_IP" >> $GITHUB_ENV
+      
 
   build_and_deploy:
     name: Build and Deploy Docker container
