Refactor deploy.yml to capture EC2 Public IP directly during Terraform Apply and fix retrieval failure

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -54,14 +54,22 @@ jobs:
     - name: Debug IP Address
       run: |
         if [[ -f apply_output.json ]]; then
-          cat apply_output.json | jq -r '.outputs.ec2_public_ip.value' > ec2_ip.txt
-          IP=$(cat ec2_ip.txt)
-          echo "EC2 Public IP is $IP"
-          if [[ -z "$IP" ]]; then
-            echo "Failed to retrieve EC2 Public IP"
+          echo "Verifying the content of apply_output.json:"
+          cat apply_output.json
+
+          # Vérifier si le fichier JSON contient bien les outputs
+          if jq -e '.outputs.ec2_public_ip.value' apply_output.json > /dev/null 2>&1; then
+            IP=$(jq -r '.outputs.ec2_public_ip.value' apply_output.json)
+            echo "EC2 Public IP is $IP"
+            if [[ -z "$IP" ]]; then
+              echo "Failed to retrieve EC2 Public IP"
+              exit 1
+            fi
+            echo "EC2_PUBLIC_IP=$IP" >> $GITHUB_ENV
+          else
+            echo "Failed to parse apply_output.json with jq"
             exit 1
           fi
-          echo "EC2_PUBLIC_IP=$IP" >> $GITHUB_ENV
         else
           echo "Failed to find apply_output.json"
           exit 1
