Refactor deploy workflow to remove AWS credentials test

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -33,7 +33,19 @@ jobs:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
-      
+
+    - name: Debug AWS Region
+      run: echo "AWS_REGION=${{ secrets.AWS_REGION }}"
+      env:
+        AWS_REGION: ${{ secrets.AWS_REGION }}    
+    
+    - name: Test AWS Credentials # Vérifier que les credentials sont corrects
+      run: |
+        aws sts get-caller-identity || (echo "Failed to verify AWS credentials" && exit 1)
+      env:
+        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
 
     - name: Terraform Plan
       run: terraform plan
